services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: parking-system
    stdin_open: true
    tty: true
    restart: "no"
    environment:
      PARKING_CAPACITY: ${PARKING_CAPACITY:-100}
      PARKING_FEE_PER_HOUR: ${PARKING_FEE_PER_HOUR:-5.0}
